    Τμήμα Πληροφορικής και Τηλεπικοινωνιών - Άρτα 
    Πανεπιστήμιο Ιωαννίνων 

    Γκόγκος Χρήστος 
    http://chgogos.github.io/
    
    Τελευταία ενημέρωση: 2/7/2022

## Το _

In [12]:
# η χρήση του _ για τη λήψη του τελευταίου αποτελέσματος

2**20

1048576

In [13]:
_

1048576

In [14]:
lambda x,y:x+y

<function __main__.<lambda>(x, y)>

In [15]:
_(1,2)

3

## Χρονομέτρηση κώδικα με το %timeit

In [16]:
n = 100000
print(sum([1.0 / i ** 2 for i in range(1, n)]))
%timeit sum([1. / i**2 for i in range(1,n)])

import numpy as np

print(np.sum(1.0 / np.arange(1.0, n) ** 2))
%timeit np.sum(1. / np.arange(1.,n) ** 2)

1.6449240667982423
29.8 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.644924066798227
858 µs ± 18.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# disassembler

In [17]:
import dis


def func(alist):
    return len(alist)


dis.dis(func)

  5           0 LOAD_GLOBAL              0 (len)
              2 LOAD_FAST                0 (alist)
              4 CALL_FUNCTION            1
              6 RETURN_VALUE


## Ισοδυναμία συναρτήσεων και λάμδα συναρτήσεων

In [18]:
import dis


def func(x, y):
    return x + y


print(dis.dis(func))

f = lambda x, y: x + y

print(dis.dis(f))

  5           0 LOAD_FAST                0 (x)
              2 LOAD_FAST                1 (y)
              4 BINARY_ADD
              6 RETURN_VALUE
None
 10           0 LOAD_FAST                0 (x)
              2 LOAD_FAST                1 (y)
              4 BINARY_ADD
              6 RETURN_VALUE
None


## Logging

In [19]:
import logging

logging.basicConfig(format="%(asctime)s %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.info("Αυτό είναι ένα μήνυμα INFO")

10:00:42 Αυτό είναι ένα μήνυμα INFO


## sys

In [20]:
import sys

print(sys.executable)

c:\Users\chgogos\.conda\envs\myenv\python.exe


## References


In [21]:
a = [0,0,0,0]
b = a # το b και το a δείχνουν στο ίδιο αντικείμενο
b[0]=42
print(a)
print(b)

[42, 0, 0, 0]
[42, 0, 0, 0]


## 2D arrays

https://www.geeksforgeeks.org/python-using-2d-arrays-lists-the-right-way/

In [22]:
# Μονοδιάστατος πίνακας
N = 5
a = [0] * N
a[0] = 1
a[1] = 2
print(a)

[1, 2, 0, 0, 0]


In [23]:
# 2d arrays in Python (example: 2X3 array of ints) - μη επιθυμητό αποτέλεσμα
# http://www.pythontutor.com/visualize.html#mode=edit

rows, cols = 2, 3
a = [[0] * cols] * rows

# η πρώτη και η δεύτερη γραμμή του πίνακα δείχνουν στο ίδιο αντικείμενο
a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a[0]==a[1]) # True
print(a)

True
[[4, 5, 6], [4, 5, 6]]


In [24]:
# 2d arrays in Python (example: 2X3 array of ints)
# http://www.pythontutor.com/visualize.html#mode=edit

rows = 2
cols = 3
a = [[0 for j in range(cols)] for  i in range(rows)]
# a = [[0] * cols  for  i in range(rows)] # η εναλλακτικά

a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a[0]==a[1]) # False
print(a)

False
[[1, 2, 3], [4, 5, 6]]


In [25]:
# 2d array με το numpy (πίνακας 2x3 με ακεραίους από το 1 μέχρι το 6)

import numpy as np

a = np.empty((2,3), dtype=np.int32)
a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a)

[[1 2 3]
 [4 5 6]]


In [26]:
# 2d array με το numpy (πίνακας 2x3 με ακεραίους από το 1 μέχρι το 6)

import numpy as np

a = np.zeros((2,3), dtype=np.int32)
a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a)

[[1 2 3]
 [4 5 6]]


In [27]:
# 2d array με το numpy (πίνακας 2x3 με ακεραίους από το 1 μέχρι το 6)

a = np.arange(1,7).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


## Magic methods

In [28]:
# magic methods (dunders)

print(1 + 2)

print(int.__add__(1, 2))

print("test".__len__())

3
3
4


## Διαχωριστικά χιλιάδων

In [29]:
# μεγάλοι αριθμοί (_ για το διαχωρισμό ψηφίων)

x = 100_000_000
print(f'{x:,}')

100,000,000


## Zip

In [30]:
# zip

a_list = ['a', 'b', 'c']
b_list = [10,20,30]

for a,b in zip(a_list, b_list):
    print(a,b)

a 10
b 20
c 30


## Αγνόηση τιμών σε αναθέσεις

In [31]:
# αγνόηση τιμής

x, _, y = 1,2,3

print(x,y)

x,y,*z = (1,2,3,4,5)

print(x,y,z)

x,y,*_, z = (1,2,3,4,5)
print(x,y,z)

1 3
1 2 [3, 4, 5]
1 2 5


In [32]:
#setattr, getattr

class Point:
    pass

p1 = Point()

setattr(p1, 'x', 5)
setattr(p1, 'y', 10)

print(p1.x, p1.y)
for k in ['x', 'y']:
    print(getattr(p1, k))

5 10
5
10


## Iterators

In [33]:
# εξάντληση iterator

a_list = ['a', 'b', 'c']
b_list = [10,20,30]

ab = zip(a_list, b_list)
print(list(ab)) # εξάντληση του iterator

for a,b in ab:
    print(a,b) 


[('a', 10), ('b', 20), ('c', 30)]


## os.walk


In [34]:
import os
for root, dirs, files in os.walk("../", topdown=False):
   for name in files:
      print(os.path.join(root, name))
   for name in dirs:
      print(os.path.join(root, name))

../automation\README.md
../concurrency\__pycache__\fib.cpython-38.pyc
../concurrency\fib.py
../concurrency\index.md
../concurrency\server-1.py
../concurrency\server-2.py
../concurrency\__pycache__
../cython_example0\build\lib.win-amd64-3.8\helloworld.cp38-win_amd64.pyd
../cython_example0\build\temp.win-amd64-3.8\Release\helloworld.cp38-win_amd64.exp
../cython_example0\build\temp.win-amd64-3.8\Release\helloworld.cp38-win_amd64.lib
../cython_example0\build\temp.win-amd64-3.8\Release\helloworld.obj
../cython_example0\build\temp.win-amd64-3.8\Release
../cython_example0\build\lib.win-amd64-3.8
../cython_example0\build\temp.win-amd64-3.8
../cython_example0\.gitignore
../cython_example0\helloworld.c
../cython_example0\helloworld.cp38-win_amd64.pyd
../cython_example0\helloworld.pyx
../cython_example0\index.md
../cython_example0\setup.py
../cython_example0\build
../cython_example1\build\lib.win-amd64-3.8\example_cy.cp38-win_amd64.pyd
../cython_example1\build\temp.win-amd64-3.8\Release\example_c

## platform

In [35]:
import platform

this_system = platform.uname()
print(this_system)
print("#"*80)
print(this_system.system)
print(this_system.node)
print(this_system.machine)
print(this_system.processor)

uname_result(system='Windows', node='DESKTOP-66P02VI', release='10', version='10.0.19044', machine='AMD64', processor='Intel64 Family 6 Model 158 Stepping 9, GenuineIntel')
################################################################################
Windows
DESKTOP-66P02VI
AMD64
Intel64 Family 6 Model 158 Stepping 9, GenuineIntel


## Συνένωση λεκτικών

In [36]:
def fun1(x):
    s = ''
    for i in range(x):
        s += str(i)
    return s
%timeit fun1(10000)

2.98 ms ± 43.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [37]:
def fun2(x):
    a_list = []
    for i in range(x):
        a_list.append(str(i))
    s = ''.join(a_list)
%timeit fun2(10000)

2.45 ms ± 115 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Function attributes

Με παρόμοιο τρόπο με τον τρόπο που θέτουμε ιδιότητες σε κλάσεις και αντικείμενα μπορούμε να θέτουμε ιδιότητες σε συναρτήσεις

In [38]:
def fun(a):
    fun.initial_value = a
    a = a * 2
    fun.intermediate_value =a
    a = a + 2
    fun.final_value = a
    return a

x = fun(3)
print(x)
print(fun.initial_value)
print(fun.intermediate_value)
print(fun.final_value)

8
3
6
8


## eval και exec

Μπορούμε να εκτελούμε δυναμικά κώδικα που έχει τοποθετηθεί σε ένα λεκτικό

H eval δέχεται μια έκφραση και επιστρέφει την τιμή της

Η exec δέχεται ένα μπλοκ κώδικα με εντολές Python και αγνοεί την τιμή που επιστρέφει η εκτέλεσή του. Τα δε αποτελέσματα λαμβάνονται μέσω των side effects που προκαλούνται από την εκτυέλεση του κώδικα.

In [39]:
x = 1
eval('x +1')

2

In [40]:
x = 1
exec('x=2')
print(x)

2


In [41]:
from functools import lru_cache

@lru_cache(maxsize=None)
def fib(x):
    if x <= 1:
        return 1
    else:
        return fib(x-1) + fib(x-2)


fib(100)

573147844013817084101

## urllib

In [42]:
# from urllib import parse

# params = {"v=":"XXXX", "t":"0m10s"}
# querystring = parse.urlencode(params)
# print(querystring)
# url = "https://..." + "?" + querystring
# resp = request.urlopen(url)

## Various

In [43]:
import re

# homeaways = "AHAHAHHHAHAAHHAHHAHAAHAHAAHAHAH"
homeaways = "AHHHAAHAH"
pattern = re.compile(r'(?=((HH)|(AA)))')
matches = pattern.finditer(homeaways)
for match in matches:
    print(match.span()[0]+1)


# results = [match.group(1) for match in re.finditer(r'(?=(HH))',homeaways)]
# print(results)

2
3
5


## Type hints

PEP484: Python will remain a dynamically typed language, and the authors have no desire to ever make type hints mandatory, even by convention.

type checker http://mypy-lang.org/

In [44]:
def fib(n):
    a, b = 0, 1
    while a < n:
        yield a
        a, b = b, a+b
fib(10)

<generator object fib at 0x000001D1169A52E0>

In [45]:
from typing import Iterator

def fib(n: int) -> Iterator[int]:
    a, b = 0, 1
    while a < n:
        yield a
        a, b = b, a+b
fib(10)

<generator object fib at 0x000001D1169A53C0>

In [46]:
def sum(a, b):
    return a+b

print(sum(1,2))
print(sum('hello ','world'))

3
hello world


In [47]:
# αν χρησιμοποιηθεί ένας typechecker όπως το mypy ή τότε θα εμφανίσει λάθος στην κλήση της συνάρτησης με οτιδήπιτε άλλο εκτός από λεκτικά

def sum(a: int, b: int) -> int:
    return a+b

print(sum(1,2))
print(sum('hello ','world'))

3
hello world


## Asterisk

In [48]:
def mult1(numbers):
    result = 1
    for x in  numbers:
        result *= x
    return result

# *numbers means any number of arguments
def mult2(*numbers):
    result = 1
    for x in  numbers:
        result *= x
    return result


mult1([1,2,3]), mult2(1,2,3)

(6, 6)

In [49]:
# unpack an iterable

x  = *range(5), 
y  = [*range(5)]
x, y

((0, 1, 2, 3, 4), [0, 1, 2, 3, 4])

In [50]:
# unpack a dictionary

a_dict = {'a':1, 'b':2}
print([*a_dict]) # unpack keys
print({**a_dict})

['a', 'b']
{'a': 1, 'b': 2}


## Μερική αποτίμηση συναρτήσεων

In [51]:
from functools import partial
from operator import add

add5 = partial(add, 5)
add5(15)

20

## Laziness in Python

[Computerphile - Laziness in Python](https://www.youtube.com/watch?v=5jwV3zxXc8E)

In [52]:
def naturals(n):
    yield n
    yield from naturals(n+1)

In [53]:
s = naturals(2)
print(next(s))
print(next(s))

2
3


In [54]:
def sieve(s):
    n = next(s)
    yield n
    yield from sieve(i for i in s if i%n!=0)

In [55]:
p = sieve(naturals(2))
print(next(p))
print(next(p))
print(next(p))
print(next(p))
print(next(p))

2
3
5
7
11


## Decorators

<https://calmcode.io/decorators/introduction.html>

In [56]:
import time
import random

def stopwatch(f):
    def func(*args, **kwargs):
        tic = time.time()
        result = f(*args, **kwargs)
        print(f"this function took: {time.time() - tic}")
        return result
    return func

def sleep_random(s=1):
    t = s + random.random()
    time.sleep(t)
    return "Done!"

timed_sleep = stopwatch(sleep_random)

# 2 functions that are similar but also different
sleep_random(), timed_sleep(), timed_sleep(2),


this function took: 1.6034808158874512
this function took: 2.8431127071380615


('Done!', 'Done!', 'Done!')

In [57]:


import time
import random
from functools import wraps

def stopwatch(f):
    @wraps(f)
    def func(*args, **kwargs):
        tic = time.time()
        result = f(*args, **kwargs)
        print(f"this function took: {time.time() - tic}")
        return result
    return func

@stopwatch
def sleep_random(s=1):
    '''This function sleeps at least for `s` seconds'''
    t = s + random.random()
    time.sleep(t)
    return f"Done"

# better syntax using @
sleep_random(), sleep_random(1), sleep_random(2)

this function took: 1.354212999343872
this function took: 1.1710214614868164
this function took: 2.82830548286438


('Done', 'Done', 'Done')

In [58]:
?sleep_random

Signature: sleep_random(s=1)
Docstring: This function sleeps at least for `s` seconds
File:      c:\users\chgogos\appdata\local\temp\ipykernel_30040\1423878574.py
Type:      function


## Εμφάνιση λίστας ακεραίων 

Με κόμματα μεταξύ των στοιχείων της λίστας

In [59]:
a_list = list(range(1,11))

# 1
for x in a_list[:-1]:
    print("{:d}".format(x), end =", "),
print(a_list[-1])

# 2
print(*a_list, sep=', ')

# 3
print(str(a_list).replace('[', '').replace(']',''))

# 4
print(str(a_list)[1:-1])

# 5
print(', '.join(map(str, a_list)))

1, 2, 3, 4, 5, 6, 7, 8, 9, 10
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
1, 2, 3, 4, 5, 6, 7, 8, 9, 10
1, 2, 3, 4, 5, 6, 7, 8, 9, 10


## Simple FP example

In [60]:
def mult(x, y):
    return x * y


a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

result = map(mult, a, b)
print(list(result))


[5, 12, 21, 32]


## Αλφάβητο στα αγγλικά και στα ελληνικά

In [61]:
# αλφάβητο στα αγγλικά (1ος τρόπος)
tmp = []
for i in range(ord('a'), ord('z')+1):
    tmp.append(chr(i))
en_alphabet = "".join(tmp)
print(en_alphabet)

# αλφάβητο στα αγγλικά (2ος τρόπος)
en_alphabet = "".join([chr(i) for i in range(ord('a'), ord('z')+1)])
print(en_alphabet)

# αλφάβητο στα αγγλικά (3ος τρόπος)
import string
print(string.ascii_lowercase)
print(string.ascii_uppercase)

# αλφάβητο στα ελληνικά (προσοχή στο ς)
el_alphabet = "".join([chr(i) for i in range(ord('α'), ord('ω')+1)])
print(el_alphabet)

# αλφάβητο στα ελληνικά
el_alphabet = "".join([chr(i) for i in range(ord('Α'), ord('Ω')+1)])
print(el_alphabet)

abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
αβγδεζηθικλμνξοπρςστυφχψω
ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡ΢ΣΤΥΦΧΨΩ


## f-strings

https://martinheinz.dev/blog/70

In [62]:
# εκτύπωση ημερομηνιών - χρόνου

import datetime
d = datetime.datetime.today()
print(f"{d:%Y-%m-%d}")
print(f"{d:%F}") 
print(f"{d:%x}") # locale preferred date

print(f"{d:%H:%M:%S}") 
print(f"{d:%T}")
print(f"{d:%X}") # locale preferred time

2022-07-02
2022-07-02
07/02/22
10:01:03
10:01:03
10:01:03


In [63]:
# εκτύπωση ονομάτων μεταβλητών μαζί με τις τιμές τους

x = 10
y = 20
print(f"x={x}, y={y}")
print(f"{x=}, {y=}") # από την έκδοση 3.8 και μετά


x=10, y=20
x=10, y=20


In [64]:
# Δεκαδικά ψηφία

x = 3.14159
print(f"{x:.2f}")
print(f"{x:10.4f}")
print(f"{x:#>10.4f}")
print(f"{x:#<10.4f}")

3.14
    3.1416
####3.1416
3.1416####


In [65]:
# padding

name = "Nikos"
age = 20

print(f"Name {name:#<20} age {age:!<20}")
print(f"Name {name:#>20} age {age:!>20}")

Name Nikos############### age 20!!!!!!!!!!!!!!!!!!
Name ###############Nikos age !!!!!!!!!!!!!!!!!!20


## Ο ρόλος της κενής συμβολοσειράς και του 0 στην if

In [66]:
# το '' και το 0 εκλαμβάνονται ως false όταν χρησιμοποιούνται στη θέση της λογικής έκφρασης της if

if not '':
    print('OK')

if 'test':
    print('OK')
    
if not 0:
    print("OK")
    
if 1:
    print("OK")

OK
OK
OK
OK
