In [ ]:
# η χρήση του _ για τη λήψη του τελευταίου αποτελέσματος

x = 2**20
_

In [20]:
# Χρονομέτρηση κώδικα με το timeit

n = 100000
print(sum([1.0 / i ** 2 for i in range(1, n)]))
%timeit sum([1. / i**2 for i in range(1,n)])

import numpy as np

%timeit np.sum(1. / np.arange(1.,n) ** 2)
print(np.sum(1.0 / np.arange(1.0, n) ** 2))

1.6449240667982423
25.8 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
857 µs ± 5.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
1.644924066798227


In [ ]:
# disassembler

import dis


def func(alist):
    return len(alist)


dis.dis(func)

In [ ]:
# ισοδυναμία συναρτήσεων και λάμδα συναρτήσεων

import dis


def func(x, y):
    return x + y


print(dis.dis(func))

f = lambda x, y: x + y

print(dis.dis(f))

In [23]:
import logging

logging.basicConfig(format="%(asctime)s %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger()
logger.setLevel(logging.INFO)
logger.info("Αυτό είναι ένα μήνυμα INFO")

19:49:39 Αυτό είναι ένα μήνυμα INFO


In [ ]:
import sys

print(sys.executable)

## References


In [39]:
a = [0,0,0,0]
b = a # το b και το a δείχνουν στο ίδιο αντικείμενο
b[0]=42
print(a)
print(b)

[42, 0, 0, 0]
[42, 0, 0, 0]


## 2D arrays

https://www.geeksforgeeks.org/python-using-2d-arrays-lists-the-right-way/

In [41]:
# Μονοδιάστατος πίνακας
N = 5
a = [0] * N
a[0] = 1
a[1] = 2
print(a)

[1, 2, 0, 0, 0]


In [37]:
# 2d arrays in Python (example: 2X3 array of ints) - μη επιθυμητό αποτέλεσμα
# http://www.pythontutor.com/visualize.html#code=rows%20%3D%202%0Acols%20%3D%203%0Aa%20%3D%20%5B%5B0%5D%20*%20cols%5D%20*%20rows%0A%0A%23%20%CE%B7%20%CF%80%CF%81%CF%8E%CF%84%CE%B7%20%CE%BA%CE%B1%CE%B9%20%CE%B7%20%CE%B4%CE%B5%CF%8D%CF%84%CE%B5%CF%81%CE%B7%20%CE%B3%CF%81%CE%B1%CE%BC%CE%BC%CE%AE%20%CF%84%CE%BF%CF%85%20%CF%80%CE%AF%CE%BD%CE%B1%CE%BA%CE%B1%20%CE%B4%CE%B5%CE%AF%CF%87%CE%BD%CE%BF%CF%85%CE%BD%20%CF%83%CF%84%CE%BF%20%CE%AF%CE%B4%CE%B9%CE%BF%20%CE%B1%CE%BD%CF%84%CE%B9%CE%BA%CE%B5%CE%AF%CE%BC%CE%B5%CE%BD%CE%BF%0Aa%5B0%5D%5B0%5D%20%3D%201%20%0Aa%5B0%5D%5B1%5D%20%3D%202%20%0Aa%5B0%5D%5B2%5D%20%3D%203%0Aa%5B1%5D%5B0%5D%20%3D%204%0Aa%5B1%5D%5B1%5D%20%3D%205%0Aa%5B1%5D%5B2%5D%20%3D%206%0Aprint%28a%5B0%5D%3D%3Da%5B1%5D%29%20%23%20True&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false

rows = 2
cols = 3
a = [[0] * cols] * rows

# η πρώτη και η δεύτερη γραμμή του πίνακα δείχνουν στο ίδιο αντικείμενο
a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a[0]==a[1]) # True
print(a)

True
[[4, 5, 6], [4, 5, 6]]


In [38]:
# 2d arrays in Python (example: 2X3 array of ints)
# http://www.pythontutor.com/visualize.html#code=%23%202d%20arrays%20in%20Python%20%28example%3A%202X3%20array%20of%20ints%29%0Arows%20%3D%202%0Acols%20%3D%203%0Aa%20%3D%20%5B%5B0%20for%20j%20in%20range%28cols%29%5D%20for%20%20i%20in%20range%28rows%29%5D%0A%23%20a%20%3D%20%5B%5B0%5D%20*%20cols%20%20for%20%20i%20in%20range%28rows%29%5D%20%23%20%CE%B7%20%CE%B5%CE%BD%CE%B1%CE%BB%CE%BB%CE%B1%CE%BA%CF%84%CE%B9%CE%BA%CE%AC%0A%0Aa%5B0%5D%5B0%5D%20%3D%201%20%0Aa%5B0%5D%5B1%5D%20%3D%202%20%0Aa%5B0%5D%5B2%5D%20%3D%203%0Aa%5B1%5D%5B0%5D%20%3D%204%0Aa%5B1%5D%5B1%5D%20%3D%205%0Aa%5B1%5D%5B2%5D%20%3D%206&cumulative=false&curInstr=0&heapPrimitives=nevernest&mode=display&origin=opt-frontend.js&py=3&rawInputLstJSON=%5B%5D&textReferences=false

rows = 2
cols = 3
a = [[0 for j in range(cols)] for  i in range(rows)]
# a = [[0] * cols  for  i in range(rows)] # η εναλλακτικά

a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a[0]==a[1]) # False
print(a)

False
[[1, 2, 3], [4, 5, 6]]


In [49]:
# 2d array με το numpy (πίνακας 2x3 με ακεραίους από το 1 μέχρι το 6)

import numpy as np

a = np.empty((2,3), dtype=np.int32)
a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a)

[[1 2 3]
 [4 5 6]]


In [58]:
# 2d array με το numpy (πίνακας 2x3 με ακεραίους από το 1 μέχρι το 6)

import numpy as np

a = np.zeros((2,3), dtype=np.int32)
a[0][0] = 1 
a[0][1] = 2 
a[0][2] = 3
a[1][0] = 4
a[1][1] = 5
a[1][2] = 6
print(a)

[[1 2 3]
 [4 5 6]]


In [59]:
# 2d array με το numpy (πίνακας 2x3 με ακεραίους από το 1 μέχρι το 6)

a = np.arange(1,7).reshape(2,3)
print(a)

[[1 2 3]
 [4 5 6]]


In [1]:
# magic methods (dunders)

print(1 + 2)

print(int.__add__(1, 2))

print("test".__len__())

3
3
4


In [8]:
# μεγάλοι αριθμοί (_ για το διαχωρισμό ψηφίων)

x = 100_000_000
print(f'{x:,}')

100,000,000


In [9]:
# zip

a_list = ['a', 'b', 'c']
b_list = [10,20,30]

for a,b in zip(a_list, b_list):
    print(a,b)

a 10
b 20
c 30


In [15]:
# αγνόηση τιμής

x, _, y = 1,2,3

print(x,y)

x,y,*z = (1,2,3,4,5)

print(x,y,z)

x,y,*_, z = (1,2,3,4,5)
print(x,y,z)

1 3
1 2 [3, 4, 5]
1 2 5


In [18]:
#setattr, getattr

class Point:
    pass

p1 = Point()

setattr(p1, 'x', 5)
setattr(p1, 'y', 10)

print(p1.x, p1.y)
for k in ['x', 'y']:
    print(getattr(p1, k))

5 10
5
10


In [21]:
# εξάντληση iterator

a_list = ['a', 'b', 'c']
b_list = [10,20,30]

ab = zip(a_list, b_list)
print(list(ab)) # εξάντληση του iterator

for a,b in ab:
    print(a,b) 


[('a', 10), ('b', 20), ('c', 30)]
